Initial commit
Anaemeribe/team-chaamy-software-testing pull request #1
Opened 2023-04-13 15:34 UTC by fuaad001

2023-04-13 15:43 UTC, Anaemeribe requested changes
Thank you for the init! Please add a .gitignore file to exclude .DS_Store files.

2023-04-13 16:21 UTC, Anaemeribe commented
Looking online I used the following to create .gitignore:
- [Typical .gitignore for a Gradle Java project](https://medium.com/@petehouston/typical-gitignore-for-a-gradle-java-project-52cbe079a99c)
- [git - Example of gitignore file for java - Stack Overflow](https://stackoverflow.com/questions/29404850/example-of-gitignore-file-for-java)
- [gitignore.io](https://www.toptal.com/developers/gitignore/api/java,gradle,intellij)

2023-04-13 19:21 UTC, Anaemeribe approved these changes

2023-04-14 04:35 UTC, ayousuf23 approved these changes

2023-04-14 04:37 UTC, merged